apiVersion: apps/v1
kind: Deployment
metadata: 
    name: mongodb
    namespace: roboshop
    # These are deployment labels
    labels: 
      component: mongodb
      project: roboshop 
      tier: database
spec: 
 replicas: 1
 # These are the labels replica set uses to create pod replicas,this should match pod labels
 selector: 
   matchLabels: 
      component: mongodb
      project: roboshop 
      tier: database
 # This is Pod definition     
 template: 
   metadata: 
     labels: 
        component: mongodb
        project: roboshop 
        tier: database
   spec: 
     containers:
       - name: mongodb
         image: jyothinaga/mongodb:v1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  #service labels 
  labels: 
     component: mongodb
     project: roboshop 
     tier: database
spec: 
  selector: 
    component: mongodb
    project: roboshop 
    tier: database 
  ports: 
   - protocol: TCP 
     port:  27017 # Service Port
     targetPort: 27017 # container port         